FROM node:alpine
WORKDIR /app

# Copy dependency list.
COPY package.json ./

# Install dependencies. This creates node_modules folder
RUN npm install

# Copy source code.
COPY . .

CMD ["npm", "run", "start"]