version: "3"
services:
  nginx:
    restart: always
    image: ramilamparo/car-rental-management-network
    build:
      context: ./nginx
    ports:
      - "${PORT}:80"
  api:
    restart: always
    image: ramilamparo/car-rental-management-server
    build:
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
      - /var/www/static:/var/www/static
    env_file:
      - car-rental-management.env
  client:
    restart: always
    image: ramilamparo/car-rental-management-client
    build:
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    env_file:
      - car-rental-management.env
