FROM nginx
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

FROM node:10
WORKDIR /app
COPY package.json ./
COPY package-lock.json ./
RUN npm install
COPY . .
EXPOSE 3000
CMD ["npm", "run", "server:prod:start"]