version: "3"
services:
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "${PORT}:80"
  api:
    restart: always
    build:
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
      - /var/www/static:/var/www/static
  client:
    restart: always
    build:
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
