FROM node:10
WORKDIR /app

# Copy dependency list.
COPY package.json ./
COPY package-lock.json ./

# Install dependencies. This creates node_modules folder
RUN npm install
# Copy source code.
COPY . .

CMD ["npm", "run", "client:start"]