enum Resource {
	BOOKINGS = "BOOKINGS",
	LOCATIONS = "LOCATIONS",
	VEHICLES = "VEHICLES",
	USERS = "USERS",
	ENUMS = "ENUMS",
	INVITES = "INVITES",
	ACCIDENTS = "ACCIDENTS",
	CLIENTS = "CLIENTS",
	CATEGORIES = "CATEGORIES"
}

export default Resource;
