enum Resource {
	BOOKINGS = "BOOKINGS",
	LOCATIONS = "LOCATIONS",
	VEHICLES = "VEHICLES",
	USERS = "USERS",
	ENUMS = "ENUMS",
	INVITES = "INVITES",
	ACCIDENTS = "ACCIDENTS"
}
export default Resource;
