const ROLES = {
	ADMIN: "ADMIN",
	KEY_MANAGER: "KEY_MANAGER",
	GUEST: "GUEST"
};

const RESOURCES = {
	BOOKINGS: "BOOKINGS",
	LOCATIONS: "LOCATIONS",
	VEHICLES: "VEHICLES",
	USERS: "USERS"
};

module.exports = { ROLES, RESOURCES };
