const ROLES = {
	ADMIN: "ADMIN",
	KEY_MANAGER: "KEY_MANAGER",
	GUEST: "GUEST"
};

const RESOURCES = {
	BOOKINGS: "BOOKINGS",
	LOCATIONS: "LOCATIONS",
	VEHICLES: "VEHICLES",
	USERS: "USERS",
	ENUMS: "ENUMS",
	INVITES: "INVITES",
	ACCIDENTS: "ACCIDENTS"
};

const BOOKING_TYPES = {
	PRIVATE: "PRIVATE",
	BUSINESS: "BUSINESS",
	SERVICE: "SERVICE",
	REPLACEMENT: "REPLACEMENT"
};

const BOOKING_STATUS = {
	UNKNOWN: "UNKNOWN",
	ONGOING: "ONGOING",
	FINISHED: "FINISHED",
	APPROVED: "APPROVED",
	EXPIRED: "EXPIRED",
	DENIED: "DENIED",
	PENDING: "PENDING"
};
const errorCodes = {
	UNAUTHORIZED: {
		message: "You do not have the permission to access this resource.",
		statusCode: 403
	}
};

module.exports = {
	ROLES,
	RESOURCES,
	BOOKING_TYPES,
	BOOKING_STATUS,
	errorCodes
};
